use anyhow::Result;
use cairo_lang_starknet_classes::contract_class::ContractClass;
use serde::{Deserialize, Serialize};
use std::{
    collections::HashMap,
    fs::{self, File},
    io::BufReader,
    path::Path,
};

use crate::{
    mappings::SierraStatementToCairoDebugInfo, ClassDebuggerData,
    ClassDebuggerDataWithContractClass,
};

// TODO: Fetch from the database
/// Fetches the debugger data for the given classes.
pub fn fetch_classes_debugger_data(
    classes: &Vec<String>,
) -> HashMap<String, ClassDebuggerDataWithContractClass> {
    let mut classes_debugger_data: HashMap<String, ClassDebuggerDataWithContractClass> =
        HashMap::new();

    let source_code = fetch_source_code(&classes);

    for class_hash in classes {
        let contract_class = load_contract_class(&class_hash);
        if let Ok(contract_class) = contract_class {
            let class_debugger_data = match source_code.get(class_hash) {
                Some(source_code) => {
                    let class_debugger_data = match load_cairo_debug_info(&class_hash) {
                        Ok(cairo_debug_info) => Some(ClassDebuggerData {
                            sierra_statements_to_cairo_info: cairo_debug_info
                                .sierra_statements_to_cairo_info,
                            source_code: source_code.clone(),
                        }),
                        Err(_) => None,
                    };
                    class_debugger_data
                }
                None => None,
            };

            classes_debugger_data.insert(
                class_hash.clone(),
                ClassDebuggerDataWithContractClass {
                    contract_class,
                    class_debugger_data,
                },
            );
        }
    }

    classes_debugger_data
}

/// Generated by modified Scarb
#[derive(Debug, Serialize, Deserialize)]
pub struct SierraToCairoDebugInfo {
    pub sierra_statements_to_cairo_info: HashMap<usize, SierraStatementToCairoDebugInfo>,
}

fn load_cairo_debug_info(class_hash: &String) -> Result<SierraToCairoDebugInfo> {
    let debug_info_file_path_str = format!("precompiled/{}/debug_info.json", class_hash);
    let debug_info_file_path = Path::new(&debug_info_file_path_str);
    let debug_info_file = File::open(debug_info_file_path)?;
    let reader = BufReader::new(debug_info_file);
    let sierra_to_cairo_debug_info = serde_json::from_reader(reader)?;
    Ok(sierra_to_cairo_debug_info)
}

fn load_contract_class(class_hash: &String) -> Result<ContractClass> {
    let file_path_str = format!("precompiled/{}/contract_class.json", class_hash);
    let file_path = Path::new(&file_path_str);
    let file = File::open(file_path)?;
    let reader = BufReader::new(file);
    let contract_class: ContractClass = serde_json::from_reader(reader)?;
    Ok(contract_class)
}

fn fetch_source_code(classes: &Vec<String>) -> HashMap<String, HashMap<String, String>> {
    let mut result_map = HashMap::new();

    for class_hash in classes {
        let mut file_map: HashMap<String, String> = HashMap::new();

        let source_code_path_str = format!("precompiled/{}/source_code", class_hash);
        let source_code_path = Path::new(&source_code_path_str);

        if source_code_path.is_dir() {
            fetch_files_recursively(source_code_path, source_code_path, &mut file_map);
        }
        result_map.insert(class_hash.clone(), file_map);
    }

    result_map
}

fn fetch_files_recursively(
    base_path: &Path,
    current_path: &Path,
    file_map: &mut HashMap<String, String>,
) {
    if current_path.is_dir() {
        for entry in fs::read_dir(current_path).expect("Failed to read directory") {
            let entry = entry.expect("Failed to read directory entry");
            let path = entry.path();
            fetch_files_recursively(base_path, &path, file_map);
        }
    } else if current_path.is_file() {
        let contents = fs::read_to_string(current_path).expect("Failed to read file");
        let relative_path = current_path
            .strip_prefix(base_path)
            .expect("Failed to get relative path");
        file_map.insert(relative_path.to_string_lossy().into_owned(), contents);
    }
}
