use crate::handlers::verification::VerificationPayload;
use crate::handlers::verification::__path_verify_handler; // Generated by utoipa
use serde::Deserialize;
use serde::Serialize;
use utoipa::OpenApi;
use utoipa::ToSchema;

#[derive(Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "snake_case")]
enum ChainId {
    SnMainnet,
    SnSepolia,
}

#[derive(OpenApi)]
#[openapi(
    paths(verify_handler,),
    components(schemas(VerificationPayload, ChainId)),
    tags((name = "Contract class verification", description = "We currently support the following cairo version & scarb version: 2.6.*")),
    info(title = "Walnut API", version = "1.0.0")
)]
pub struct ApiDoc;
