use crate::handlers::classes::GetClassResponse;
use crate::handlers::classes::GetClassResponseWithSourceCode;
use crate::handlers::classes::__path_get_class_handler; // Generated by utoipa
use crate::handlers::classes::__path_get_class_handler_with_chain_id; // Generated by utoipa
use crate::handlers::contracts::ContractAbiResponse;
use crate::handlers::contracts::ContractResponseWithSourceCode;
use crate::handlers::contracts::__path_get_contract_entrypoints_handler;
use crate::handlers::contracts::__path_get_contract_handler; // Generated by utoipa
use crate::handlers::search::SearchResponse;
use crate::handlers::search::__path_get_search_handler; //Generated by utoipa
use crate::handlers::verification::VerificationPayload;
use crate::handlers::verification::VerificationPayloadWithRpc;
use crate::handlers::verification::VerificationStatusResponse;
use crate::handlers::verification::__path_get_verification_status_handler; // Generated by utoipa
use crate::handlers::verification::__path_verify_handler; // Generated by utoipa
use crate::handlers::verification::__path_verify_handler_with_rpc; // Generated by utoipa
use serde::Deserialize;
use serde::Serialize;
use utoipa::OpenApi;
use utoipa::ToSchema;

#[derive(Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "snake_case")]
enum ChainId {
    SnMain,
    SnSepolia,
}

#[derive(OpenApi)]
#[openapi(
    paths(verify_handler,get_verification_status_handler,get_class_handler_with_chain_id,get_class_handler,verify_handler_with_rpc, get_contract_handler, get_contract_entrypoints_handler, get_search_handler),
    components(schemas(VerificationPayload, ChainId, GetClassResponse, GetClassResponseWithSourceCode, VerificationPayloadWithRpc, ContractResponseWithSourceCode, ContractAbiResponse, SearchResponse, VerificationStatusResponse)),
    tags((name = "Contract class verification", description = "We currently support the following cairo version & scarb version: 2.6.*")),
    info(title = "Walnut API", version = "1.1.0")
)]
pub struct ApiDoc;
