use crate::handlers::classes::GetClassResponse;
use crate::handlers::classes::GetClassResponseWithSourceCode;
use crate::handlers::classes::__path_get_class_handler; // Generated by utoipa
use crate::handlers::classes::__path_get_class_handler_with_chain_id; // Generated by utoipa
use crate::handlers::verification::VerificationPayload;
use crate::handlers::verification::VerificationPayloadWithRpc;
use crate::handlers::verification::__path_verify_handler; // Generated by utoipa
use crate::handlers::verification::__path_verify_handler_with_rpc; // Generated by utoipa
use serde::Deserialize;
use serde::Serialize;
use utoipa::OpenApi;
use utoipa::ToSchema;

#[derive(Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "snake_case")]
enum ChainId {
    SnMainnet,
    SnSepolia,
}

#[derive(OpenApi)]
#[openapi(
    paths(verify_handler,get_class_handler_with_chain_id,get_class_handler,verify_handler_with_rpc),
    components(schemas(VerificationPayload, ChainId, GetClassResponse, GetClassResponseWithSourceCode, VerificationPayloadWithRpc)),
    tags((name = "Contract class verification", description = "We currently support the following cairo version & scarb version: 2.6.*")),
    info(title = "Walnut API", version = "1.1.0")
)]
pub struct ApiDoc;
