use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Generated by modified Scarb
#[derive(Debug, Serialize, Deserialize)]
pub struct SierraToCairoDebugInfo {
    pub sierra_statements_to_cairo_info: HashMap<usize, SierraStatementToCairoDebugInfo>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct SierraStatementToCairoDebugInfo {
    pub cairo_locations: Vec<CodeLocation>,
}

/// Human readable position inside a file, in lines and characters.
#[derive(Debug, Serialize, Clone, Deserialize, Hash, Eq, PartialEq)]
pub struct TextPosition {
    /// Line index, 0 based.
    pub line: usize,
    /// Character index inside the line, 0 based.
    pub col: usize,
}

#[derive(Debug, Serialize, Clone, Deserialize, Hash, Eq, PartialEq)]
pub struct CodeLocation {
    pub start: TextPosition,
    pub end: TextPosition,
    pub file_path: String,
}
