pub mod db;
pub mod s3;
pub mod utils;
pub mod verification;

use cairo_lang_starknet_classes::contract_class::ContractClass;
use serde::{Deserialize, Serialize};
use sqlx::Type;
use std::collections::HashMap;
use std::fmt;
use time::PrimitiveDateTime;
use uuid::Uuid;

pub const SUPPORTED_VERSIONS: &[(u32, u32, u32)] = &[(2, 6, 3), (2, 6, 4), (2, 7, 0)];

#[derive(Debug, Serialize, Deserialize, Type, PartialEq, Eq)]
#[sqlx(type_name = "verification_status", rename_all = "lowercase")] // Assuming PostgreSQL
pub enum EVerificationStatus {
    Pending,
    Success,
    Failed,
}

impl fmt::Display for EVerificationStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            EVerificationStatus::Pending => write!(f, "pending"),
            EVerificationStatus::Success => write!(f, "success"),
            EVerificationStatus::Failed => write!(f, "failed"),
        }
    }
}

#[derive(Debug)]
pub struct VerificationStatusRow {
    pub id: Uuid,
    pub network: Option<String>,
    pub class_hash: Option<String>,
    pub status: EVerificationStatus,
    pub error_message: Option<String>,
    pub created_at: PrimitiveDateTime,
    pub updated_at: PrimitiveDateTime,
}

#[derive(Debug)]
pub struct VerifiedClassRow {
    pub hash: String,
    pub is_sierra_debug_info: bool,
    pub is_cairo_debug_info: bool,
    pub is_source_code: bool,
    pub chain_id: Option<String>,
    pub project_id: Option<i32>,
}

#[derive(Serialize, Deserialize)]
pub struct VerifiedClassData {
    pub contract_class: ContractClass,
    pub cairo_debug_info: Option<SierraToCairoDebugInfo>,
    pub source_code: HashMap<String, String>,
}

/// Generated by modified Scarb
#[derive(Debug, Serialize, Deserialize)]
pub struct SierraToCairoDebugInfo {
    pub sierra_statements_to_cairo_info: HashMap<usize, SierraStatementToCairoDebugInfo>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct SierraStatementToCairoDebugInfo {
    pub cairo_locations: Vec<CodeLocation>,
}

/// Human readable position inside a file, in lines and characters.
#[derive(Debug, Serialize, Clone, Deserialize, Hash, Eq, PartialEq)]
pub struct TextPosition {
    /// Line index, 0 based.
    pub line: usize,
    /// Character index inside the line, 0 based.
    pub col: usize,
}

#[derive(Debug, Serialize, Clone, Deserialize, Hash, Eq, PartialEq)]
pub struct CodeLocation {
    pub start: TextPosition,
    pub end: TextPosition,
    pub file_path: String,
}
