pub mod artifacts;
pub mod db;
pub mod helpers;
pub mod manifest;
pub mod minimal_verification;
pub mod s3;
pub mod scarb;
pub mod scarb_and_dojo_download_scheduler;
pub mod utils;
pub mod verification;

use anyhow::Result;
use cairo_lang_starknet_classes::contract_class::ContractClass;
use serde::{Deserialize, Serialize};
use sqlx::Type;
use starknet_rust::core::types::Felt;
use std::collections::HashMap;
use std::fmt;
use std::path::PathBuf;
use time::PrimitiveDateTime;
use uuid::Uuid;

/// The key is a `String` representing the class hash.
/// The value is a `Result` containing a tuple with the following elements:
/// - `String`: The class name.
/// - `Vec<Felt>`: The program from the network.
/// - `(u32, u32, u32)`: The Cairo version from the network.
/// - `Option<ContractClass>`: The Sierra contract class compiled from the source code.
/// - `Option<String>`: The class_hash that is caluclated with inline strategy on
/// - `Option<PathBuf>`: The path to the debug info file compiled from the source code.
/// - `Option<SierraToCairoDebugInfo>`: The Cairo debug info compiled from the source code.
type ClassVerificationData = HashMap<
    String,
    Result<(
        String,
        Vec<Felt>,
        (u32, u32, u32),
        Option<ContractClass>,
        Option<String>,
        Option<PathBuf>,
        Option<SierraToCairoDebugInfo>,
    )>,
>;

#[derive(Debug, Serialize, Deserialize, Type, PartialEq, Eq, Clone)]
#[sqlx(type_name = "verification_status", rename_all = "lowercase")] // Assuming PostgreSQL
pub enum EVerificationStatus {
    Pending,
    Success,
    Failed,
}

impl fmt::Display for EVerificationStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            EVerificationStatus::Pending => write!(f, "pending"),
            EVerificationStatus::Success => write!(f, "success"),
            EVerificationStatus::Failed => write!(f, "failed"),
        }
    }
}

impl EVerificationStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            EVerificationStatus::Pending => "pending",
            EVerificationStatus::Success => "success",
            EVerificationStatus::Failed => "failed",
        }
    }
}

#[derive(Debug)]
pub struct VerificationStatusRow {
    pub primary_id: i32,
    pub id: Uuid,
    pub network: Option<String>,
    pub class_hash: Option<String>,
    pub status: EVerificationStatus,
    pub message: Option<String>,
    pub project_id: Option<i32>,
    pub created_at: PrimitiveDateTime,
    pub updated_at: PrimitiveDateTime,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct VerificationStatusSerializable {
    pub primary_id: i32,
    pub id: String,
    pub network: Option<String>,
    pub class_hash: Option<String>,
    pub status: EVerificationStatus,
    pub message: Option<String>,
    pub project_id: Option<i32>,
    pub created_at: String,
    pub updated_at: String,
    pub profiles: Option<Vec<String>>,
}

impl VerificationStatusSerializable {
    pub fn from_rows(rows: Vec<VerificationStatusRow>) -> Vec<Self> {
        rows.into_iter()
            .map(VerificationStatusSerializable::from)
            .collect()
    }
}

impl From<VerificationStatusRow> for VerificationStatusSerializable {
    fn from(row: VerificationStatusRow) -> Self {
        VerificationStatusSerializable {
            primary_id: row.primary_id,
            id: row.id.to_string(),
            network: row.network,
            class_hash: row.class_hash,
            status: row.status,
            message: row.message,
            project_id: row.project_id,
            created_at: row.created_at.to_string(),
            updated_at: row.updated_at.to_string(),
            profiles: None,
        }
    }
}

#[derive(Debug)]
pub struct VerifiedClassRow {
    pub hash: String,
    pub is_sierra_debug_info: bool,
    pub is_cairo_debug_info: bool,
    pub is_source_code: bool,
    pub chain_id: Option<String>,
    pub project_id: Option<i32>,
}

#[derive(Serialize, Deserialize)]
pub struct VerifiedClassData {
    pub contract_class: ContractClass,
    pub cairo_debug_info: Option<SierraToCairoDebugInfo>, // Deprecated. Use contract_class.sierra_program_debug_info.annotations.github.com/software-mansion/cairo-coverage.statements_code_locations
    pub source_code: HashMap<String, String>,
}

/// Generated by modified Scarb
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct SierraToCairoDebugInfo {
    pub sierra_statements_to_cairo_info: HashMap<usize, SierraStatementToCairoDebugInfo>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct SierraStatementToCairoDebugInfo {
    pub cairo_locations: Vec<CodeLocation>,
}

/// Human readable position inside a file, in lines and characters.
#[derive(Debug, Serialize, Clone, Deserialize, Hash, Eq, PartialEq)]
pub struct TextPosition {
    /// Line index, 0 based.
    pub line: usize,
    /// Character index inside the line, 0 based.
    pub col: usize,
}

impl TextPosition {
    pub fn from_coverage(
        coverage_code_location: cairo_annotations::annotations::coverage::SourceCodeLocation,
    ) -> Self {
        TextPosition {
            line: coverage_code_location.line.0,
            col: coverage_code_location.col.0,
        }
    }
}

#[derive(Debug, Serialize, Clone, Deserialize, Hash, Eq, PartialEq)]
pub struct CodeLocation {
    pub start: TextPosition,
    pub end: TextPosition,
    pub file_path: String,
}

impl CodeLocation {
    pub fn from_coverage(
        coverage_code_location: cairo_annotations::annotations::coverage::CodeLocation,
    ) -> Self {
        CodeLocation {
            start: TextPosition::from_coverage(coverage_code_location.1.start),
            end: TextPosition::from_coverage(coverage_code_location.1.end),
            file_path: coverage_code_location.0 .0.to_string(),
        }
    }
}

#[derive(Debug, Serialize, Deserialize)]
pub struct VerificationRequestRow {
    pub id: Uuid,
    pub status: Option<String>,
    pub message: Option<String>,
    pub created_at: PrimitiveDateTime,
    pub updated_at: PrimitiveDateTime,
    pub cairo_version: Option<String>,
    pub package_name: Option<String>,
}
