[package]
name = "simulate"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
blockifier.workspace = true
starknet.workspace = true
starknet_api.workspace = true
num-traits.workspace = true
num-bigint.workspace = true
sqlx.workspace = true
cheatnet.workspace = true
runtime.workspace = true
url.workspace = true
tokio.workspace = true
cairo-vm.workspace = true
internal-tracing.workspace = true
walnut-shared.workspace = true
serde_json.workspace = true
futures.workspace = true
