[package]
name = "internal-tracing"
version = "1.0.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
blockifier.workspace = true
starknet_api.workspace = true
cairo-lang-starknet-classes.workspace = true
cairo-vm.workspace = true
serde_json.workspace = true
serde.workspace = true
num-bigint.workspace = true
cairo-lang-casm.workspace = true
cairo-lang-sierra.workspace = true
cairo-lang-sierra-to-casm.workspace = true
cairo-lang-sierra-type-size.workspace = true
data-decoder.workspace = true
sqlx.workspace = true
aws-sdk-s3.workspace = true
aws-smithy-types.workspace = true
verification.workspace = true
futures.workspace = true
walnut-shared.workspace = true
indexmap.workspace = true
cairo-lang-utils.workspace = true
num-traits.workspace = true
starknet-types-core.workspace = true
smol_str.workspace = true
starknet.workspace = true
itertools.workspace = true
tracing.workspace = true
cairo-annotations.workspace = true
byteorder = "1.5.0"
indextree = "4.6.1"
