[package]
name = "internal-tracing"
version = "1.0.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
blockifier.workspace = true
starknet_api.workspace = true
cairo-felt.workspace = true
cairo-lang-starknet-classes.workspace = true
cairo-vm.workspace = true
serde_json.workspace = true
serde.workspace = true
num-bigint.workspace = true
cairo-lang-casm.workspace = true
cairo-lang-sierra.workspace = true
cairo-lang-sierra-to-casm.workspace = true
cairo-lang-sierra-type-size.workspace = true
sqlx.workspace = true
aws-sdk-s3.workspace = true
aws-smithy-types.workspace = true
verification.workspace = true
futures.workspace = true
walnut-shared.workspace = true
itertools = "0.12.1"
byteorder = "1.5.0"
indextree = "4.6.1"
smol_str = "0.2.1"
