[package]
name = "walnut-shared"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Shared types, ABI helpers and RPC utilities for the walnut-server workspace."

[dependencies]
url.workspace = true
starknet_api.workspace = true
num-bigint.workspace = true
serde.workspace = true
serde_json.workspace = true
blockifier.workspace = true
cairo-vm.workspace = true
cairo-lang-sierra.workspace = true
conversions.workspace = true
cheatnet.workspace = true
starknet-rust.workspace = true
hex.workspace = true
anyhow.workspace = true
cairo-lang-utils.workspace = true
num-traits.workspace = true
smol_str.workspace = true
thiserror.workspace = true
cairo-lang-starknet-classes.workspace = true
num-integer.workspace = true
starknet-types-core.workspace = true
starknet-selector-decoder.workspace = true
ethers.workspace = true
reqwest.workspace = true
urlencoding.workspace = true
