[package]
name = "walnut-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
url.workspace = true
starknet-providers.workspace = true
starknet_api.workspace = true
num-bigint.workspace = true
cairo-felt.workspace = true
serde.workspace = true
cairo-vm.workspace = true
cairo-lang-sierra.workspace = true
conversions.workspace = true
cheatnet.workspace = true
starknet.workspace = true
hex.workspace = true
anyhow.workspace = true
