[package]
name = "server"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "HTTP API for Starknet transaction simulation, debugging and contract verification."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
db = { path = "../db" }
utoipa.workspace = true
axum.workspace = true
sqlx.workspace = true
tower.workspace = true
tower-http.workspace = true
tokio.workspace = true
serde.workspace = true
dotenv.workspace = true
reqwest.workspace = true
serde_json.workspace = true
url.workspace = true
uuid.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
starknet-rust.workspace = true
starknet_api.workspace = true
blockifier.workspace = true
simulate.workspace = true
axum-prometheus = "0.4.0"
cookie.workspace = true
jsonwebtoken.workspace = true
urlencoding.workspace = true
cheatnet.workspace = true
futures.workspace = true
cairo-vm.workspace = true
scarb-api.workspace = true
cairo-lang-starknet-classes.workspace = true
anyhow.workspace = true
walnut-shared.workspace = true
data-decoder.workspace = true
verification.workspace = true
num-traits.workspace = true
num-bigint.workspace = true
google-cloud-storage.workspace = true
sentry.workspace = true
sentry-tracing.workspace = true
sentry-tower.workspace = true
clokwerk.workspace = true
chrono.workspace = true
time.workspace = true
ethers.workspace = true
toml.workspace = true
internal-tracing.workspace = true
moka = { version = "0.12", features = ["future"] }
sha2 = "0.10"
subtle = "2.5"

[dev-dependencies]
tower = { workspace = true, features = ["util"] }
google-cloud-auth.workspace = true
